name: Build Naming Binary

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            artifact-name: naming-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact-name: naming-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact-name: naming-macos

    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Initialize submodules for hbb_common

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75.0
          targets: ${{ matrix.target }}

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        shell: pwsh

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake
          brew install python
          brew install pkg-config gstreamer  # Install GStreamer for macOS
        shell: bash

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               clang \
               cmake \
               curl \
               gcc-multilib \
               git \
               g++ \
               g++-multilib \
               libayatana-appindicator3-dev \
               libasound2-dev \
               libc6-dev \
               libclang-10-dev \
               libgstreamer1.0-dev \
               libgstreamer-plugins-base1.0-dev \
               libgtk-3-dev \
               libpam0g-dev \
               libpulse-dev \
               libva-dev \
               libxcb-randr0-dev \
               libxcb-shape0-dev \
               libxcb-xfixes0-dev \
               libxdo-dev \
               libxfixes-dev \
               llvm-10-dev \
               nasm \
               ninja-build \
               openjdk-17-jdk-headless \
               pkg-config \
               tree \
               wget
        shell: bash

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build naming binary (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo build --bin naming --release --target ${{ matrix.target }}
        shell: pwsh
        env:
          CARGO_INCREMENTAL: 0
          CARGO_TERM_COLOR: always

      - name: Build naming binary (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: cargo build --bin naming --release --target ${{ matrix.target }}
        shell: bash
        env:
          CARGO_INCREMENTAL: 0
          CARGO_TERM_COLOR: always

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact-name }}
          if-no-files-found: error
